language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_26f0785ea309_key -iv $encrypted_26f0785ea309_iv -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
